### ISSUE TITLE
How to use in a storyboard

### ISSUE THREAD

**Issue by blkbam** [sgwilly/RangeSlider#2]
How can I get this to show up in a storyboard? I attempted to mark the RangeSlider class as IBDesignable and assign it to a UIView however at runtime the control doesn't render.

**Comment by digitalturtle** [comment]
@blkbam did you get this working? I would also like to use it on storyboard but have not been able to do so. I guess something needs to be implemented in here:

    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }

to actually set it up and make it render

**Comment by blkbam** [comment]
@digitalturtle I abandoned it for https://github.com/TomThorpe/TTRangeSlider

**Comment by sgwilly** [comment]
@blkbam @digitalturtle Hi guys,
Thanks for having given RangeSlider a try.
I just made it **IBDesignable**, so it shows up in storyboards and is rendered properly at runtime.
